hibernate:
  connection:
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/denis-matveenko-db
    username: postgres
    password: s9td3ixh
    provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    characterEncoding: utf8
    useUnicode: true
  jdbc:
    show_sql: true
    format_sql: true
    batch_size: 50


  hbm2ddl:
    auto: create
  hikari:
    minimumIdle: 5
    maximumPoolSize: 10
    idleTimeout: 30000
    connectionTimeout: 30000
    leakDetectionThreshold: 60000
  cache:
    use_second_level_cache: false
  non_contextual_lob_creation: true
  type:
    preferred_enum_type: string
  physical_naming_strategy: com.dmdev.util.SnakeCaseNamingStrategy
  dialect: org.hibernate.dialect.PostgreSQLDialect
  connection_pool_size: 10
  current_session_context_class: thread
  show_sql: true
  format_sql: true
  use_sql_comments: true


